### ISSUE TITLE
V3-lm-pool

### ISSUE THREAD

**Issue by satyasai69** [pancakeswap/pancake-v3-contracts#21]
IPancakeV3LmPoolDeveloper.sol missing

**Comment by vashisht67** [comment]
@satyasai69 plz check the code`// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity >=0.5.0;

interface IPancakeV3LmPoolDeveloper {
    function parameters() external view returns (address pool, address masterChef);
}`

**Comment by ChefSnoopy** [comment]
already added, thanks
